// Code generated by "stringer -type=DataType -linecomment"; DO NOT EDIT.

package domain

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DataTypeUnknown-0]
	_ = x[DataTypeCredentials-1]
	_ = x[DataTypeText-2]
	_ = x[DataTypeBinary-3]
	_ = x[DataTypeCard-4]
	_ = x[DataTypeOTP-5]
}

const _DataType_name = "unknowncredentialstextbinarycardotp"

var _DataType_index = [...]uint8{0, 7, 18, 22, 28, 32, 35}

func (i DataType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_DataType_index)-1 {
		return "DataType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DataType_name[_DataType_index[idx]:_DataType_index[idx+1]]
}
